version: "3.7"

services:
    web-application:
        container_name: flask-app
        build: .
        environment:
            HOST: db
            PORT: 3306
            DBNAME: climate
            DB_USER: root
            DB_PASSWORD: root123
            LOG_LEVEL: ERROR
        ports:
            - "5000:5000"

    db:
        container_name: climate-db
        image: mysql:8.0.21
        ports:
            - "30000:3306"
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro
        environment:
            MYSQL_ROOT_PASSWORD: root123